language: php

php:
  - 7.1

services:
    - redis
    - mysql

before_script:
    - mysql -e 'create database symfony;'
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
    - bin/console doctrine:schema:create --env=test
#    - app/console doctrine:migrations:migrate --env=test --no-interaction --quiet
    - bin/console cache:warmup --env=test

script:
    - bin/console server:run --env=test
    - ./vendor/bin/codecept run --coverage-xml

after_success:
    - if [[ ! -z $coverage ]]; then coveralls; fi
    - php vendor/bin/coveralls -v'
