// flow-typed signature: 5ec18ed0ad97c7000666895761d60f2b
// flow-typed version: <<STUB>>/babel-plugin-transform-vue-jsx_v^3.4.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-vue-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-vue-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-vue-jsx/dist/babel-plugin-transform-vue-jsx.min' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-vue-jsx/lib/group-props' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-vue-jsx/lib/make-map' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-vue-jsx/dist/babel-plugin-transform-vue-jsx.min.js' {
  declare module.exports: $Exports<'babel-plugin-transform-vue-jsx/dist/babel-plugin-transform-vue-jsx.min'>;
}
declare module 'babel-plugin-transform-vue-jsx/index' {
  declare module.exports: $Exports<'babel-plugin-transform-vue-jsx'>;
}
declare module 'babel-plugin-transform-vue-jsx/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-vue-jsx'>;
}
declare module 'babel-plugin-transform-vue-jsx/lib/group-props.js' {
  declare module.exports: $Exports<'babel-plugin-transform-vue-jsx/lib/group-props'>;
}
declare module 'babel-plugin-transform-vue-jsx/lib/make-map.js' {
  declare module.exports: $Exports<'babel-plugin-transform-vue-jsx/lib/make-map'>;
}
