// flow-typed signature: 2db9fc7d3ff5dcd3ccca9b1fd58115d2
// flow-typed version: <<STUB>>/bootstrap-datepicker_v^1.7.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-datepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-datepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-datepicker/dist/js/bootstrap-datepicker' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/js/bootstrap-datepicker.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker-en-CA.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ar-tn.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ar.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.az.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bg.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bn.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.br.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bs.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ca.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.cs.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.cy.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.da.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.de.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.el.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-AU.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-GB.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-IE.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-NZ.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-ZA.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.eo.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.es.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.et.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.eu.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fa.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fi.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fo.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fr-CH.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fr.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.gl.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.he.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hi.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hr.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hu.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hy.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.id.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.is.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.it-CH.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.it.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ja.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ka.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.kh.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.kk.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.km.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ko.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.kr.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.lt.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.lv.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.me.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.mk.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.mn.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ms.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.nb.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.nl-BE.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.nl.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.no.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.oc.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pl.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt-BR.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ro.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.rs-latin.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.rs.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ru.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.si.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sk.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sl.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sq.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sr-latin.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sr.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sv.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sw.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ta.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.tg.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.th.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.tr.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uk.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uz-cyrl.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uz-latn.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.vi.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-TW.min' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/bootstrap-datepicker' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker-en-CA' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ar-tn' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ar' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.az' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.bg' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.bn' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.br' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.bs' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ca' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.cs' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.cy' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.da' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.de' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.el' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-AU' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-GB' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-IE' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-NZ' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-ZA' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.eo' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.es' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.et' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.eu' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.fa' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.fi' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.fo' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.fr-CH' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.fr' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.gl' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.he' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.hi' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.hr' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.hu' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.hy' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.id' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.is' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.it-CH' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.it' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ja' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ka' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.kh' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.kk' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.km' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ko' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.kr' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.lt' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.lv' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.me' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.mk' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.mn' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ms' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.nb' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.nl-BE' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.nl' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.no' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.oc' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.pl' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.pt' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ro' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.rs-latin' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.rs' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ru' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.si' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sk' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sl' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sq' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sr-latin' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sr' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sv' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sw' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ta' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.tg' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.th' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.tr' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.uk' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.uz-cyrl' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.uz-latn' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.vi' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.zh-CN' {
  declare module.exports: any;
}

declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.zh-TW' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-datepicker/dist/js/bootstrap-datepicker.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/js/bootstrap-datepicker'>;
}
declare module 'bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/js/bootstrap-datepicker.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker-en-CA.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker-en-CA.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ar-tn.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ar-tn.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ar.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ar.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.az.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.az.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bg.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bg.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bn.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bn.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.br.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.br.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bs.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.bs.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ca.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ca.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.cs.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.cs.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.cy.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.cy.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.da.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.da.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.de.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.de.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.el.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.el.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-AU.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-AU.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-GB.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-GB.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-IE.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-IE.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-NZ.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-NZ.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-ZA.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.en-ZA.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.eo.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.eo.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.es.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.es.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.et.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.et.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.eu.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.eu.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fa.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fa.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fi.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fi.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fo.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fo.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fr-CH.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fr-CH.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fr.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.fr.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.gl.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.gl.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.he.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.he.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hi.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hi.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hr.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hr.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hu.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hu.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hy.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.hy.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.id.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.id.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.is.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.is.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.it-CH.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.it-CH.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.it.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.it.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ja.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ja.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ka.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ka.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.kh.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.kh.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.kk.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.kk.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.km.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.km.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ko.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ko.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.kr.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.kr.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.lt.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.lt.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.lv.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.lv.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.me.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.me.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.mk.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.mk.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.mn.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.mn.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ms.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ms.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.nb.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.nb.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.nl-BE.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.nl-BE.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.nl.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.nl.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.no.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.no.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.oc.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.oc.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pl.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pl.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt-BR.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt-BR.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ro.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ro.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.rs-latin.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.rs-latin.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.rs.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.rs.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ru.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ru.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.si.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.si.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sk.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sk.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sl.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sl.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sq.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sq.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sr-latin.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sr-latin.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sr.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sr.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sv.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sv.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sw.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.sw.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ta.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.ta.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.tg.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.tg.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.th.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.th.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.tr.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.tr.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uk.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uk.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uz-cyrl.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uz-cyrl.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uz-latn.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.uz-latn.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.vi.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.vi.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min'>;
}
declare module 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-TW.min.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-TW.min'>;
}
declare module 'bootstrap-datepicker/js/bootstrap-datepicker.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/bootstrap-datepicker'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker-en-CA.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker-en-CA'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ar-tn.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.ar-tn'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ar.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.ar'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.az.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.az'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.bg.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.bg'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.bn.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.bn'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.br.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.br'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.bs.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.bs'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ca.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.ca'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.cs.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.cs'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.cy.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.cy'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.da.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.da'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.de.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.de'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.el.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.el'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-AU.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-AU'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-GB.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-GB'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-IE.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-IE'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-NZ.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-NZ'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-ZA.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.en-ZA'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.eo.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.eo'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.es.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.es'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.et.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.et'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.eu.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.eu'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.fa.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.fa'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.fi.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.fi'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.fo.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.fo'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.fr-CH.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.fr-CH'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.fr.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.fr'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.gl.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.gl'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.he.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.he'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.hi.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.hi'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.hr.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.hr'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.hu.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.hu'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.hy.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.hy'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.id.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.id'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.is.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.is'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.it-CH.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.it-CH'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.it.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.it'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ja.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.ja'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ka.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.ka'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.kh.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.kh'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.kk.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.kk'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.km.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.km'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ko.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.ko'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.kr.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.kr'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.lt.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.lt'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.lv.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.lv'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.me.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.me'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.mk.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.mk'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.mn.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.mn'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ms.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.ms'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.nb.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.nb'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.nl-BE.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.nl-BE'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.nl.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.nl'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.no.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.no'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.oc.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.oc'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.pl.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.pl'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.pt.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.pt'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ro.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.ro'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.rs-latin.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.rs-latin'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.rs.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.rs'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ru.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.ru'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.si.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.si'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sk.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.sk'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sl.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.sl'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sq.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.sq'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sr-latin.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.sr-latin'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sr.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.sr'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sv.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.sv'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.sw.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.sw'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.ta.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.ta'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.tg.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.tg'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.th.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.th'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.tr.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.tr'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.uk.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.uk'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.uz-cyrl.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.uz-cyrl'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.uz-latn.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.uz-latn'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.vi.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.vi'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.zh-CN.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.zh-CN'>;
}
declare module 'bootstrap-datepicker/js/locales/bootstrap-datepicker.zh-TW.js' {
  declare module.exports: $Exports<'bootstrap-datepicker/js/locales/bootstrap-datepicker.zh-TW'>;
}
