// flow-typed signature: 71bb58e4e95c89ba22c2094ba92fc3de
// flow-typed version: <<STUB>>/cropperjs_v^1.0.0-rc.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cropperjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cropperjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cropperjs/dist/cropper.common' {
  declare module.exports: any;
}

declare module 'cropperjs/dist/cropper.esm' {
  declare module.exports: any;
}

declare module 'cropperjs/dist/cropper' {
  declare module.exports: any;
}

declare module 'cropperjs/dist/cropper.min' {
  declare module.exports: any;
}

declare module 'cropperjs/src/js/change' {
  declare module.exports: any;
}

declare module 'cropperjs/src/js/cropper' {
  declare module.exports: any;
}

declare module 'cropperjs/src/js/defaults' {
  declare module.exports: any;
}

declare module 'cropperjs/src/js/events' {
  declare module.exports: any;
}

declare module 'cropperjs/src/js/handlers' {
  declare module.exports: any;
}

declare module 'cropperjs/src/js/methods' {
  declare module.exports: any;
}

declare module 'cropperjs/src/js/preview' {
  declare module.exports: any;
}

declare module 'cropperjs/src/js/render' {
  declare module.exports: any;
}

declare module 'cropperjs/src/js/template' {
  declare module.exports: any;
}

declare module 'cropperjs/src/js/utilities' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cropperjs/dist/cropper.common.js' {
  declare module.exports: $Exports<'cropperjs/dist/cropper.common'>;
}
declare module 'cropperjs/dist/cropper.esm.js' {
  declare module.exports: $Exports<'cropperjs/dist/cropper.esm'>;
}
declare module 'cropperjs/dist/cropper.js' {
  declare module.exports: $Exports<'cropperjs/dist/cropper'>;
}
declare module 'cropperjs/dist/cropper.min.js' {
  declare module.exports: $Exports<'cropperjs/dist/cropper.min'>;
}
declare module 'cropperjs/src/js/change.js' {
  declare module.exports: $Exports<'cropperjs/src/js/change'>;
}
declare module 'cropperjs/src/js/cropper.js' {
  declare module.exports: $Exports<'cropperjs/src/js/cropper'>;
}
declare module 'cropperjs/src/js/defaults.js' {
  declare module.exports: $Exports<'cropperjs/src/js/defaults'>;
}
declare module 'cropperjs/src/js/events.js' {
  declare module.exports: $Exports<'cropperjs/src/js/events'>;
}
declare module 'cropperjs/src/js/handlers.js' {
  declare module.exports: $Exports<'cropperjs/src/js/handlers'>;
}
declare module 'cropperjs/src/js/methods.js' {
  declare module.exports: $Exports<'cropperjs/src/js/methods'>;
}
declare module 'cropperjs/src/js/preview.js' {
  declare module.exports: $Exports<'cropperjs/src/js/preview'>;
}
declare module 'cropperjs/src/js/render.js' {
  declare module.exports: $Exports<'cropperjs/src/js/render'>;
}
declare module 'cropperjs/src/js/template.js' {
  declare module.exports: $Exports<'cropperjs/src/js/template'>;
}
declare module 'cropperjs/src/js/utilities.js' {
  declare module.exports: $Exports<'cropperjs/src/js/utilities'>;
}
