// flow-typed signature: ac3b0bae07784c8fd112991d0c816edd
// flow-typed version: <<STUB>>/envify_v^3.4.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'envify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'envify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'envify/custom' {
  declare module.exports: any;
}

declare module 'envify/visitors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'envify/custom.js' {
  declare module.exports: $Exports<'envify/custom'>;
}
declare module 'envify/index' {
  declare module.exports: $Exports<'envify'>;
}
declare module 'envify/index.js' {
  declare module.exports: $Exports<'envify'>;
}
declare module 'envify/visitors.js' {
  declare module.exports: $Exports<'envify/visitors'>;
}
