// flow-typed signature: eefcd21d27f9b60cb87415e71238bb84
// flow-typed version: <<STUB>>/eslint-plugin-vue-libs_v^1.2.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-vue-libs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-vue-libs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-vue-libs/config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue-libs/rules/jsx-uses-vars' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-vue-libs/config.js' {
  declare module.exports: $Exports<'eslint-plugin-vue-libs/config'>;
}
declare module 'eslint-plugin-vue-libs/index' {
  declare module.exports: $Exports<'eslint-plugin-vue-libs'>;
}
declare module 'eslint-plugin-vue-libs/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vue-libs'>;
}
declare module 'eslint-plugin-vue-libs/rules/jsx-uses-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-vue-libs/rules/jsx-uses-vars'>;
}
