// flow-typed signature: 476ef72c7886aa24d638a03206e4381d
// flow-typed version: <<STUB>>/howler_v^2.0.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'howler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'howler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'howler/dist/howler.core.min' {
  declare module.exports: any;
}

declare module 'howler/dist/howler' {
  declare module.exports: any;
}

declare module 'howler/dist/howler.min' {
  declare module.exports: any;
}

declare module 'howler/dist/howler.spatial.min' {
  declare module.exports: any;
}

declare module 'howler/src/howler.core' {
  declare module.exports: any;
}

declare module 'howler/src/plugins/howler.spatial' {
  declare module.exports: any;
}

// Filename aliases
declare module 'howler/dist/howler.core.min.js' {
  declare module.exports: $Exports<'howler/dist/howler.core.min'>;
}
declare module 'howler/dist/howler.js' {
  declare module.exports: $Exports<'howler/dist/howler'>;
}
declare module 'howler/dist/howler.min.js' {
  declare module.exports: $Exports<'howler/dist/howler.min'>;
}
declare module 'howler/dist/howler.spatial.min.js' {
  declare module.exports: $Exports<'howler/dist/howler.spatial.min'>;
}
declare module 'howler/src/howler.core.js' {
  declare module.exports: $Exports<'howler/src/howler.core'>;
}
declare module 'howler/src/plugins/howler.spatial.js' {
  declare module.exports: $Exports<'howler/src/plugins/howler.spatial'>;
}
