// flow-typed signature: 70bcebceadbb848c889158ed96fdd6ed
// flow-typed version: <<STUB>>/less-plugin-rewrite-import_v^0.1.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-plugin-rewrite-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-plugin-rewrite-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'less-plugin-rewrite-import/lib/index' {
  declare module.exports: any;
}

declare module 'less-plugin-rewrite-import/lib/parse-options' {
  declare module.exports: any;
}

declare module 'less-plugin-rewrite-import/lib/rewrite-manager' {
  declare module.exports: any;
}

declare module 'less-plugin-rewrite-import/lib/usage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'less-plugin-rewrite-import/lib/index.js' {
  declare module.exports: $Exports<'less-plugin-rewrite-import/lib/index'>;
}
declare module 'less-plugin-rewrite-import/lib/parse-options.js' {
  declare module.exports: $Exports<'less-plugin-rewrite-import/lib/parse-options'>;
}
declare module 'less-plugin-rewrite-import/lib/rewrite-manager.js' {
  declare module.exports: $Exports<'less-plugin-rewrite-import/lib/rewrite-manager'>;
}
declare module 'less-plugin-rewrite-import/lib/usage.js' {
  declare module.exports: $Exports<'less-plugin-rewrite-import/lib/usage'>;
}
