// flow-typed signature: 31ab43a671d090eda781c8deb07157e5
// flow-typed version: <<STUB>>/metismenu_v^2.7.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'metismenu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'metismenu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'metismenu/dist/metisMenu' {
  declare module.exports: any;
}

declare module 'metismenu/dist/metisMenu.min' {
  declare module.exports: any;
}

declare module 'metismenu/src/import' {
  declare module.exports: any;
}

declare module 'metismenu/src/metisMenu' {
  declare module.exports: any;
}

// Filename aliases
declare module 'metismenu/dist/metisMenu.js' {
  declare module.exports: $Exports<'metismenu/dist/metisMenu'>;
}
declare module 'metismenu/dist/metisMenu.min.js' {
  declare module.exports: $Exports<'metismenu/dist/metisMenu.min'>;
}
declare module 'metismenu/src/import.js' {
  declare module.exports: $Exports<'metismenu/src/import'>;
}
declare module 'metismenu/src/metisMenu.js' {
  declare module.exports: $Exports<'metismenu/src/metisMenu'>;
}
