// flow-typed signature: 33db0277b93af4d4e472e6a77a764b0a
// flow-typed version: <<STUB>>/quill-delta-markdown_vhttps://github.com/pollend/quill-delta-markdown.git/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'quill-delta-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'quill-delta-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'quill-delta-markdown/dist/quill-delta-markdown' {
  declare module.exports: any;
}

declare module 'quill-delta-markdown/src/fromDelta' {
  declare module.exports: any;
}

declare module 'quill-delta-markdown/src/index' {
  declare module.exports: any;
}

declare module 'quill-delta-markdown/src/toDelta' {
  declare module.exports: any;
}

declare module 'quill-delta-markdown/test/fromDelta' {
  declare module.exports: any;
}

declare module 'quill-delta-markdown/test/index' {
  declare module.exports: any;
}

declare module 'quill-delta-markdown/test/toDelta' {
  declare module.exports: any;
}

declare module 'quill-delta-markdown/test/toDeltaSpec' {
  declare module.exports: any;
}

declare module 'quill-delta-markdown/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'quill-delta-markdown/dist/quill-delta-markdown.js' {
  declare module.exports: $Exports<'quill-delta-markdown/dist/quill-delta-markdown'>;
}
declare module 'quill-delta-markdown/src/fromDelta.js' {
  declare module.exports: $Exports<'quill-delta-markdown/src/fromDelta'>;
}
declare module 'quill-delta-markdown/src/index.js' {
  declare module.exports: $Exports<'quill-delta-markdown/src/index'>;
}
declare module 'quill-delta-markdown/src/toDelta.js' {
  declare module.exports: $Exports<'quill-delta-markdown/src/toDelta'>;
}
declare module 'quill-delta-markdown/test/fromDelta.js' {
  declare module.exports: $Exports<'quill-delta-markdown/test/fromDelta'>;
}
declare module 'quill-delta-markdown/test/index.js' {
  declare module.exports: $Exports<'quill-delta-markdown/test/index'>;
}
declare module 'quill-delta-markdown/test/toDelta.js' {
  declare module.exports: $Exports<'quill-delta-markdown/test/toDelta'>;
}
declare module 'quill-delta-markdown/test/toDeltaSpec.js' {
  declare module.exports: $Exports<'quill-delta-markdown/test/toDeltaSpec'>;
}
declare module 'quill-delta-markdown/webpack.config.js' {
  declare module.exports: $Exports<'quill-delta-markdown/webpack.config'>;
}
