// flow-typed signature: 8ff709bcc52e48f1edb569033606c517
// flow-typed version: <<STUB>>/quill_v^1.2.6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'quill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'quill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'quill/blots/block' {
  declare module.exports: any;
}

declare module 'quill/blots/break' {
  declare module.exports: any;
}

declare module 'quill/blots/container' {
  declare module.exports: any;
}

declare module 'quill/blots/cursor' {
  declare module.exports: any;
}

declare module 'quill/blots/embed' {
  declare module.exports: any;
}

declare module 'quill/blots/inline' {
  declare module.exports: any;
}

declare module 'quill/blots/scroll' {
  declare module.exports: any;
}

declare module 'quill/blots/text' {
  declare module.exports: any;
}

declare module 'quill/core' {
  declare module.exports: any;
}

declare module 'quill/core/editor' {
  declare module.exports: any;
}

declare module 'quill/core/emitter' {
  declare module.exports: any;
}

declare module 'quill/core/logger' {
  declare module.exports: any;
}

declare module 'quill/core/module' {
  declare module.exports: any;
}

declare module 'quill/core/polyfill' {
  declare module.exports: any;
}

declare module 'quill/core/quill' {
  declare module.exports: any;
}

declare module 'quill/core/selection' {
  declare module.exports: any;
}

declare module 'quill/core/theme' {
  declare module.exports: any;
}

declare module 'quill/dist/quill.core' {
  declare module.exports: any;
}

declare module 'quill/dist/quill' {
  declare module.exports: any;
}

declare module 'quill/dist/quill.min' {
  declare module.exports: any;
}

declare module 'quill/formats/align' {
  declare module.exports: any;
}

declare module 'quill/formats/background' {
  declare module.exports: any;
}

declare module 'quill/formats/blockquote' {
  declare module.exports: any;
}

declare module 'quill/formats/bold' {
  declare module.exports: any;
}

declare module 'quill/formats/code' {
  declare module.exports: any;
}

declare module 'quill/formats/color' {
  declare module.exports: any;
}

declare module 'quill/formats/direction' {
  declare module.exports: any;
}

declare module 'quill/formats/font' {
  declare module.exports: any;
}

declare module 'quill/formats/header' {
  declare module.exports: any;
}

declare module 'quill/formats/image' {
  declare module.exports: any;
}

declare module 'quill/formats/indent' {
  declare module.exports: any;
}

declare module 'quill/formats/italic' {
  declare module.exports: any;
}

declare module 'quill/formats/link' {
  declare module.exports: any;
}

declare module 'quill/formats/list' {
  declare module.exports: any;
}

declare module 'quill/formats/script' {
  declare module.exports: any;
}

declare module 'quill/formats/size' {
  declare module.exports: any;
}

declare module 'quill/formats/strike' {
  declare module.exports: any;
}

declare module 'quill/formats/underline' {
  declare module.exports: any;
}

declare module 'quill/formats/video' {
  declare module.exports: any;
}

declare module 'quill/modules/clipboard' {
  declare module.exports: any;
}

declare module 'quill/modules/formula' {
  declare module.exports: any;
}

declare module 'quill/modules/history' {
  declare module.exports: any;
}

declare module 'quill/modules/keyboard' {
  declare module.exports: any;
}

declare module 'quill/modules/syntax' {
  declare module.exports: any;
}

declare module 'quill/modules/toolbar' {
  declare module.exports: any;
}

declare module 'quill/quill' {
  declare module.exports: any;
}

declare module 'quill/themes/base' {
  declare module.exports: any;
}

declare module 'quill/themes/bubble' {
  declare module.exports: any;
}

declare module 'quill/themes/snow' {
  declare module.exports: any;
}

declare module 'quill/ui/color-picker' {
  declare module.exports: any;
}

declare module 'quill/ui/icon-picker' {
  declare module.exports: any;
}

declare module 'quill/ui/icons' {
  declare module.exports: any;
}

declare module 'quill/ui/picker' {
  declare module.exports: any;
}

declare module 'quill/ui/tooltip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'quill/blots/block.js' {
  declare module.exports: $Exports<'quill/blots/block'>;
}
declare module 'quill/blots/break.js' {
  declare module.exports: $Exports<'quill/blots/break'>;
}
declare module 'quill/blots/container.js' {
  declare module.exports: $Exports<'quill/blots/container'>;
}
declare module 'quill/blots/cursor.js' {
  declare module.exports: $Exports<'quill/blots/cursor'>;
}
declare module 'quill/blots/embed.js' {
  declare module.exports: $Exports<'quill/blots/embed'>;
}
declare module 'quill/blots/inline.js' {
  declare module.exports: $Exports<'quill/blots/inline'>;
}
declare module 'quill/blots/scroll.js' {
  declare module.exports: $Exports<'quill/blots/scroll'>;
}
declare module 'quill/blots/text.js' {
  declare module.exports: $Exports<'quill/blots/text'>;
}
declare module 'quill/core.js' {
  declare module.exports: $Exports<'quill/core'>;
}
declare module 'quill/core/editor.js' {
  declare module.exports: $Exports<'quill/core/editor'>;
}
declare module 'quill/core/emitter.js' {
  declare module.exports: $Exports<'quill/core/emitter'>;
}
declare module 'quill/core/logger.js' {
  declare module.exports: $Exports<'quill/core/logger'>;
}
declare module 'quill/core/module.js' {
  declare module.exports: $Exports<'quill/core/module'>;
}
declare module 'quill/core/polyfill.js' {
  declare module.exports: $Exports<'quill/core/polyfill'>;
}
declare module 'quill/core/quill.js' {
  declare module.exports: $Exports<'quill/core/quill'>;
}
declare module 'quill/core/selection.js' {
  declare module.exports: $Exports<'quill/core/selection'>;
}
declare module 'quill/core/theme.js' {
  declare module.exports: $Exports<'quill/core/theme'>;
}
declare module 'quill/dist/quill.core.js' {
  declare module.exports: $Exports<'quill/dist/quill.core'>;
}
declare module 'quill/dist/quill.js' {
  declare module.exports: $Exports<'quill/dist/quill'>;
}
declare module 'quill/dist/quill.min.js' {
  declare module.exports: $Exports<'quill/dist/quill.min'>;
}
declare module 'quill/formats/align.js' {
  declare module.exports: $Exports<'quill/formats/align'>;
}
declare module 'quill/formats/background.js' {
  declare module.exports: $Exports<'quill/formats/background'>;
}
declare module 'quill/formats/blockquote.js' {
  declare module.exports: $Exports<'quill/formats/blockquote'>;
}
declare module 'quill/formats/bold.js' {
  declare module.exports: $Exports<'quill/formats/bold'>;
}
declare module 'quill/formats/code.js' {
  declare module.exports: $Exports<'quill/formats/code'>;
}
declare module 'quill/formats/color.js' {
  declare module.exports: $Exports<'quill/formats/color'>;
}
declare module 'quill/formats/direction.js' {
  declare module.exports: $Exports<'quill/formats/direction'>;
}
declare module 'quill/formats/font.js' {
  declare module.exports: $Exports<'quill/formats/font'>;
}
declare module 'quill/formats/header.js' {
  declare module.exports: $Exports<'quill/formats/header'>;
}
declare module 'quill/formats/image.js' {
  declare module.exports: $Exports<'quill/formats/image'>;
}
declare module 'quill/formats/indent.js' {
  declare module.exports: $Exports<'quill/formats/indent'>;
}
declare module 'quill/formats/italic.js' {
  declare module.exports: $Exports<'quill/formats/italic'>;
}
declare module 'quill/formats/link.js' {
  declare module.exports: $Exports<'quill/formats/link'>;
}
declare module 'quill/formats/list.js' {
  declare module.exports: $Exports<'quill/formats/list'>;
}
declare module 'quill/formats/script.js' {
  declare module.exports: $Exports<'quill/formats/script'>;
}
declare module 'quill/formats/size.js' {
  declare module.exports: $Exports<'quill/formats/size'>;
}
declare module 'quill/formats/strike.js' {
  declare module.exports: $Exports<'quill/formats/strike'>;
}
declare module 'quill/formats/underline.js' {
  declare module.exports: $Exports<'quill/formats/underline'>;
}
declare module 'quill/formats/video.js' {
  declare module.exports: $Exports<'quill/formats/video'>;
}
declare module 'quill/modules/clipboard.js' {
  declare module.exports: $Exports<'quill/modules/clipboard'>;
}
declare module 'quill/modules/formula.js' {
  declare module.exports: $Exports<'quill/modules/formula'>;
}
declare module 'quill/modules/history.js' {
  declare module.exports: $Exports<'quill/modules/history'>;
}
declare module 'quill/modules/keyboard.js' {
  declare module.exports: $Exports<'quill/modules/keyboard'>;
}
declare module 'quill/modules/syntax.js' {
  declare module.exports: $Exports<'quill/modules/syntax'>;
}
declare module 'quill/modules/toolbar.js' {
  declare module.exports: $Exports<'quill/modules/toolbar'>;
}
declare module 'quill/quill.js' {
  declare module.exports: $Exports<'quill/quill'>;
}
declare module 'quill/themes/base.js' {
  declare module.exports: $Exports<'quill/themes/base'>;
}
declare module 'quill/themes/bubble.js' {
  declare module.exports: $Exports<'quill/themes/bubble'>;
}
declare module 'quill/themes/snow.js' {
  declare module.exports: $Exports<'quill/themes/snow'>;
}
declare module 'quill/ui/color-picker.js' {
  declare module.exports: $Exports<'quill/ui/color-picker'>;
}
declare module 'quill/ui/icon-picker.js' {
  declare module.exports: $Exports<'quill/ui/icon-picker'>;
}
declare module 'quill/ui/icons.js' {
  declare module.exports: $Exports<'quill/ui/icons'>;
}
declare module 'quill/ui/picker.js' {
  declare module.exports: $Exports<'quill/ui/picker'>;
}
declare module 'quill/ui/tooltip.js' {
  declare module.exports: $Exports<'quill/ui/tooltip'>;
}
