// flow-typed signature: 8e0c9df6ed996b979df8ce735e055326
// flow-typed version: <<STUB>>/throttle-debounce_v^1.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'throttle-debounce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'throttle-debounce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'throttle-debounce/debounce' {
  declare module.exports: any;
}

declare module 'throttle-debounce/karma.conf' {
  declare module.exports: any;
}

declare module 'throttle-debounce/test/index' {
  declare module.exports: any;
}

declare module 'throttle-debounce/throttle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'throttle-debounce/debounce.js' {
  declare module.exports: $Exports<'throttle-debounce/debounce'>;
}
declare module 'throttle-debounce/index' {
  declare module.exports: $Exports<'throttle-debounce'>;
}
declare module 'throttle-debounce/index.js' {
  declare module.exports: $Exports<'throttle-debounce'>;
}
declare module 'throttle-debounce/karma.conf.js' {
  declare module.exports: $Exports<'throttle-debounce/karma.conf'>;
}
declare module 'throttle-debounce/test/index.js' {
  declare module.exports: $Exports<'throttle-debounce/test/index'>;
}
declare module 'throttle-debounce/throttle.js' {
  declare module.exports: $Exports<'throttle-debounce/throttle'>;
}
