// flow-typed signature: 2d8163514d8ef518c3e569b41b48e154
// flow-typed version: <<STUB>>/toastr_v^2.1.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'toastr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'toastr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'toastr/build/toastr.min' {
  declare module.exports: any;
}

declare module 'toastr/gulpfile' {
  declare module.exports: any;
}

declare module 'toastr/karma.conf' {
  declare module.exports: any;
}

declare module 'toastr/nuget/content/scripts/toastr' {
  declare module.exports: any;
}

declare module 'toastr/nuget/content/scripts/toastr.min' {
  declare module.exports: any;
}

declare module 'toastr/package/build/toastr.min' {
  declare module.exports: any;
}

declare module 'toastr/package/gulpfile' {
  declare module.exports: any;
}

declare module 'toastr/package/karma.conf' {
  declare module.exports: any;
}

declare module 'toastr/package/nuget/content/scripts/toastr' {
  declare module.exports: any;
}

declare module 'toastr/package/nuget/content/scripts/toastr.min' {
  declare module.exports: any;
}

declare module 'toastr/package/package/build/toastr.min' {
  declare module.exports: any;
}

declare module 'toastr/package/package/gulpfile' {
  declare module.exports: any;
}

declare module 'toastr/package/package/karma.conf' {
  declare module.exports: any;
}

declare module 'toastr/package/package/nuget/content/scripts/toastr' {
  declare module.exports: any;
}

declare module 'toastr/package/package/nuget/content/scripts/toastr.min' {
  declare module.exports: any;
}

declare module 'toastr/package/package/tests/qunit/qunit' {
  declare module.exports: any;
}

declare module 'toastr/package/package/tests/unit/qunit-helper' {
  declare module.exports: any;
}

declare module 'toastr/package/package/tests/unit/toastr-tests' {
  declare module.exports: any;
}

declare module 'toastr/package/package/tests/unit/x' {
  declare module.exports: any;
}

declare module 'toastr/package/package/toastr' {
  declare module.exports: any;
}

declare module 'toastr/package/tests/qunit/qunit' {
  declare module.exports: any;
}

declare module 'toastr/package/tests/unit/qunit-helper' {
  declare module.exports: any;
}

declare module 'toastr/package/tests/unit/toastr-tests' {
  declare module.exports: any;
}

declare module 'toastr/package/tests/unit/x' {
  declare module.exports: any;
}

declare module 'toastr/package/toastr' {
  declare module.exports: any;
}

declare module 'toastr/tests/qunit/qunit' {
  declare module.exports: any;
}

declare module 'toastr/tests/unit/qunit-helper' {
  declare module.exports: any;
}

declare module 'toastr/tests/unit/toastr-tests' {
  declare module.exports: any;
}

declare module 'toastr/tests/unit/x' {
  declare module.exports: any;
}

declare module 'toastr/toastr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'toastr/build/toastr.min.js' {
  declare module.exports: $Exports<'toastr/build/toastr.min'>;
}
declare module 'toastr/gulpfile.js' {
  declare module.exports: $Exports<'toastr/gulpfile'>;
}
declare module 'toastr/karma.conf.js' {
  declare module.exports: $Exports<'toastr/karma.conf'>;
}
declare module 'toastr/nuget/content/scripts/toastr.js' {
  declare module.exports: $Exports<'toastr/nuget/content/scripts/toastr'>;
}
declare module 'toastr/nuget/content/scripts/toastr.min.js' {
  declare module.exports: $Exports<'toastr/nuget/content/scripts/toastr.min'>;
}
declare module 'toastr/package/build/toastr.min.js' {
  declare module.exports: $Exports<'toastr/package/build/toastr.min'>;
}
declare module 'toastr/package/gulpfile.js' {
  declare module.exports: $Exports<'toastr/package/gulpfile'>;
}
declare module 'toastr/package/karma.conf.js' {
  declare module.exports: $Exports<'toastr/package/karma.conf'>;
}
declare module 'toastr/package/nuget/content/scripts/toastr.js' {
  declare module.exports: $Exports<'toastr/package/nuget/content/scripts/toastr'>;
}
declare module 'toastr/package/nuget/content/scripts/toastr.min.js' {
  declare module.exports: $Exports<'toastr/package/nuget/content/scripts/toastr.min'>;
}
declare module 'toastr/package/package/build/toastr.min.js' {
  declare module.exports: $Exports<'toastr/package/package/build/toastr.min'>;
}
declare module 'toastr/package/package/gulpfile.js' {
  declare module.exports: $Exports<'toastr/package/package/gulpfile'>;
}
declare module 'toastr/package/package/karma.conf.js' {
  declare module.exports: $Exports<'toastr/package/package/karma.conf'>;
}
declare module 'toastr/package/package/nuget/content/scripts/toastr.js' {
  declare module.exports: $Exports<'toastr/package/package/nuget/content/scripts/toastr'>;
}
declare module 'toastr/package/package/nuget/content/scripts/toastr.min.js' {
  declare module.exports: $Exports<'toastr/package/package/nuget/content/scripts/toastr.min'>;
}
declare module 'toastr/package/package/tests/qunit/qunit.js' {
  declare module.exports: $Exports<'toastr/package/package/tests/qunit/qunit'>;
}
declare module 'toastr/package/package/tests/unit/qunit-helper.js' {
  declare module.exports: $Exports<'toastr/package/package/tests/unit/qunit-helper'>;
}
declare module 'toastr/package/package/tests/unit/toastr-tests.js' {
  declare module.exports: $Exports<'toastr/package/package/tests/unit/toastr-tests'>;
}
declare module 'toastr/package/package/tests/unit/x.js' {
  declare module.exports: $Exports<'toastr/package/package/tests/unit/x'>;
}
declare module 'toastr/package/package/toastr.js' {
  declare module.exports: $Exports<'toastr/package/package/toastr'>;
}
declare module 'toastr/package/tests/qunit/qunit.js' {
  declare module.exports: $Exports<'toastr/package/tests/qunit/qunit'>;
}
declare module 'toastr/package/tests/unit/qunit-helper.js' {
  declare module.exports: $Exports<'toastr/package/tests/unit/qunit-helper'>;
}
declare module 'toastr/package/tests/unit/toastr-tests.js' {
  declare module.exports: $Exports<'toastr/package/tests/unit/toastr-tests'>;
}
declare module 'toastr/package/tests/unit/x.js' {
  declare module.exports: $Exports<'toastr/package/tests/unit/x'>;
}
declare module 'toastr/package/toastr.js' {
  declare module.exports: $Exports<'toastr/package/toastr'>;
}
declare module 'toastr/tests/qunit/qunit.js' {
  declare module.exports: $Exports<'toastr/tests/qunit/qunit'>;
}
declare module 'toastr/tests/unit/qunit-helper.js' {
  declare module.exports: $Exports<'toastr/tests/unit/qunit-helper'>;
}
declare module 'toastr/tests/unit/toastr-tests.js' {
  declare module.exports: $Exports<'toastr/tests/unit/toastr-tests'>;
}
declare module 'toastr/tests/unit/x.js' {
  declare module.exports: $Exports<'toastr/tests/unit/x'>;
}
declare module 'toastr/toastr.js' {
  declare module.exports: $Exports<'toastr/toastr'>;
}
