// flow-typed signature: d298b5272d378728330ff3ba384def19
// flow-typed version: <<STUB>>/translated_v^0.3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'translated'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'translated' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'translated/dist/index' {
  declare module.exports: any;
}

declare module 'translated/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'translated/dist/index.js' {
  declare module.exports: $Exports<'translated/dist/index'>;
}
declare module 'translated/tests/index.js' {
  declare module.exports: $Exports<'translated/tests/index'>;
}
