// flow-typed signature: b08ac2b7c6ead6aced8144f367b720c6
// flow-typed version: <<STUB>>/ts-loader_v^2.0.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ts-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ts-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ts-loader/dist/after-compile' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/compilerSetup' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/config' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/constants' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/index' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/instances' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/interfaces' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/logger' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/resolver' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/servicesHost' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/utils' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/watch-run' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/fork-ts-checker/webpack.config' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/happypack/webpack.config' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/clean' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/inject' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/staticFiles' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/tests' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/webpack' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulpFile' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/karma.conf' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config.base' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config.prod' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/clean' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/inject' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/staticFiles' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/tests' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/webpack' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulpFile' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/karma.conf' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/test/main' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config.base' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config.prod' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp/gulp/clean' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp/gulp/inject' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp/gulp/staticFiles' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp/gulp/tests' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp/gulp/webpack' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp/gulpFile' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp/karma.conf' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp/webpack.config.base' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp/webpack.config' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-babel-karma-gulp/webpack.config.prod' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/react-cdn-simple/webpack.config' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/vanilla/webpack.config' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/clean' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/inject' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/staticFiles' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/tests' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/webpack' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulpFile' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/karma.conf' {
  declare module.exports: any;
}

declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ts-loader/dist/after-compile.js' {
  declare module.exports: $Exports<'ts-loader/dist/after-compile'>;
}
declare module 'ts-loader/dist/compilerSetup.js' {
  declare module.exports: $Exports<'ts-loader/dist/compilerSetup'>;
}
declare module 'ts-loader/dist/config.js' {
  declare module.exports: $Exports<'ts-loader/dist/config'>;
}
declare module 'ts-loader/dist/constants.js' {
  declare module.exports: $Exports<'ts-loader/dist/constants'>;
}
declare module 'ts-loader/dist/index.js' {
  declare module.exports: $Exports<'ts-loader/dist/index'>;
}
declare module 'ts-loader/dist/instances.js' {
  declare module.exports: $Exports<'ts-loader/dist/instances'>;
}
declare module 'ts-loader/dist/interfaces.js' {
  declare module.exports: $Exports<'ts-loader/dist/interfaces'>;
}
declare module 'ts-loader/dist/logger.js' {
  declare module.exports: $Exports<'ts-loader/dist/logger'>;
}
declare module 'ts-loader/dist/resolver.js' {
  declare module.exports: $Exports<'ts-loader/dist/resolver'>;
}
declare module 'ts-loader/dist/servicesHost.js' {
  declare module.exports: $Exports<'ts-loader/dist/servicesHost'>;
}
declare module 'ts-loader/dist/utils.js' {
  declare module.exports: $Exports<'ts-loader/dist/utils'>;
}
declare module 'ts-loader/dist/watch-run.js' {
  declare module.exports: $Exports<'ts-loader/dist/watch-run'>;
}
declare module 'ts-loader/examples/fork-ts-checker/webpack.config.js' {
  declare module.exports: $Exports<'ts-loader/examples/fork-ts-checker/webpack.config'>;
}
declare module 'ts-loader/examples/happypack/webpack.config.js' {
  declare module.exports: $Exports<'ts-loader/examples/happypack/webpack.config'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/clean.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/clean'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/inject.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/inject'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/staticFiles.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/staticFiles'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/tests.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/tests'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/webpack.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulp/webpack'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulpFile.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/gulpFile'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/karma.conf.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/karma.conf'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config.base.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config.base'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config.dev.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config.dev'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config.prod.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-fork-ts-checker/webpack.config.prod'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/clean.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/clean'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/inject.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/inject'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/staticFiles.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/staticFiles'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/tests.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/tests'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/webpack.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/gulp/webpack'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/gulpFile.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/gulpFile'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/karma.conf.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/karma.conf'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/test/main.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/test/main'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config.base.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config.base'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config.dev.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config.dev'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config.prod.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp-happypack/webpack.config.prod'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp/gulp/clean.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp/gulp/clean'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp/gulp/inject.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp/gulp/inject'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp/gulp/staticFiles.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp/gulp/staticFiles'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp/gulp/tests.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp/gulp/tests'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp/gulp/webpack.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp/gulp/webpack'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp/gulpFile.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp/gulpFile'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp/karma.conf.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp/karma.conf'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp/webpack.config.base.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp/webpack.config.base'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp/webpack.config.dev.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp/webpack.config.dev'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp/webpack.config.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp/webpack.config'>;
}
declare module 'ts-loader/examples/react-babel-karma-gulp/webpack.config.prod.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-babel-karma-gulp/webpack.config.prod'>;
}
declare module 'ts-loader/examples/react-cdn-simple/webpack.config.js' {
  declare module.exports: $Exports<'ts-loader/examples/react-cdn-simple/webpack.config'>;
}
declare module 'ts-loader/examples/vanilla/webpack.config.js' {
  declare module.exports: $Exports<'ts-loader/examples/vanilla/webpack.config'>;
}
declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/clean.js' {
  declare module.exports: $Exports<'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/clean'>;
}
declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/inject.js' {
  declare module.exports: $Exports<'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/inject'>;
}
declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/staticFiles.js' {
  declare module.exports: $Exports<'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/staticFiles'>;
}
declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/tests.js' {
  declare module.exports: $Exports<'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/tests'>;
}
declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/webpack.js' {
  declare module.exports: $Exports<'ts-loader/examples/webpack1/react-babel-karma-gulp/gulp/webpack'>;
}
declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/gulpFile.js' {
  declare module.exports: $Exports<'ts-loader/examples/webpack1/react-babel-karma-gulp/gulpFile'>;
}
declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/karma.conf.js' {
  declare module.exports: $Exports<'ts-loader/examples/webpack1/react-babel-karma-gulp/karma.conf'>;
}
declare module 'ts-loader/examples/webpack1/react-babel-karma-gulp/webpack.config.js' {
  declare module.exports: $Exports<'ts-loader/examples/webpack1/react-babel-karma-gulp/webpack.config'>;
}
declare module 'ts-loader/index' {
  declare module.exports: $Exports<'ts-loader'>;
}
declare module 'ts-loader/index.js' {
  declare module.exports: $Exports<'ts-loader'>;
}
