// flow-typed signature: e061e56e94179657bcac32346e244dd5
// flow-typed version: <<STUB>>/typo-js_v^1.0.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typo-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typo-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typo-js/typo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typo-js/typo.js' {
  declare module.exports: $Exports<'typo-js/typo'>;
}
