// flow-typed signature: cafac58f2ada83f39cb57e5fab43f2f2
// flow-typed version: <<STUB>>/vee-validate_v^2.0.0-rc.7/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vee-validate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vee-validate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vee-validate/dist/locale/ar' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ca' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/da' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/de' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/el' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/en' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/es' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/et' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/fa' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/fi' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/fr' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/he' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/hr' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/hu' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/id' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/it' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ja' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ka' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ko' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/lt' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/nb_NO' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/nl' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/nn_NO' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/pl' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/pt_BR' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ro' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ru' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/sk' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/sl' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/sv' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/tr' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/ua' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/uk' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/vi' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/zh_CN' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/locale/zh_TW' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/vee-validate.esm' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/vee-validate' {
  declare module.exports: any;
}

declare module 'vee-validate/dist/vee-validate.min' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/dictionary' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/errorBag' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/helpers/index' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/helpersTest' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/listeners' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/after' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/alpha_dash' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/alpha_num' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/alpha_spaces' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/alpha' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/before' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/between' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/confirmed' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/credit_card' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/date_between' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/date_format' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/decimal' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/digits' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/dimensions' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/email' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/ext' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/image' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/in' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/ip' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/max_value' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/max' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/mimes' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/min_value' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/min' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/not_in' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/numeric' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/regex' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/required' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/size' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/rules/url' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/utils' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/validator.1' {
  declare module.exports: any;
}

declare module 'vee-validate/tests/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vee-validate/dist/locale/ar.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ar'>;
}
declare module 'vee-validate/dist/locale/ca.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ca'>;
}
declare module 'vee-validate/dist/locale/da.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/da'>;
}
declare module 'vee-validate/dist/locale/de.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/de'>;
}
declare module 'vee-validate/dist/locale/el.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/el'>;
}
declare module 'vee-validate/dist/locale/en.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/en'>;
}
declare module 'vee-validate/dist/locale/es.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/es'>;
}
declare module 'vee-validate/dist/locale/et.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/et'>;
}
declare module 'vee-validate/dist/locale/fa.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/fa'>;
}
declare module 'vee-validate/dist/locale/fi.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/fi'>;
}
declare module 'vee-validate/dist/locale/fr.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/fr'>;
}
declare module 'vee-validate/dist/locale/he.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/he'>;
}
declare module 'vee-validate/dist/locale/hr.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/hr'>;
}
declare module 'vee-validate/dist/locale/hu.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/hu'>;
}
declare module 'vee-validate/dist/locale/id.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/id'>;
}
declare module 'vee-validate/dist/locale/it.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/it'>;
}
declare module 'vee-validate/dist/locale/ja.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ja'>;
}
declare module 'vee-validate/dist/locale/ka.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ka'>;
}
declare module 'vee-validate/dist/locale/ko.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ko'>;
}
declare module 'vee-validate/dist/locale/lt.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/lt'>;
}
declare module 'vee-validate/dist/locale/nb_NO.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/nb_NO'>;
}
declare module 'vee-validate/dist/locale/nl.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/nl'>;
}
declare module 'vee-validate/dist/locale/nn_NO.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/nn_NO'>;
}
declare module 'vee-validate/dist/locale/pl.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/pl'>;
}
declare module 'vee-validate/dist/locale/pt_BR.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/pt_BR'>;
}
declare module 'vee-validate/dist/locale/ro.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ro'>;
}
declare module 'vee-validate/dist/locale/ru.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ru'>;
}
declare module 'vee-validate/dist/locale/sk.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/sk'>;
}
declare module 'vee-validate/dist/locale/sl.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/sl'>;
}
declare module 'vee-validate/dist/locale/sv.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/sv'>;
}
declare module 'vee-validate/dist/locale/tr.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/tr'>;
}
declare module 'vee-validate/dist/locale/ua.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/ua'>;
}
declare module 'vee-validate/dist/locale/uk.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/uk'>;
}
declare module 'vee-validate/dist/locale/vi.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/vi'>;
}
declare module 'vee-validate/dist/locale/zh_CN.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/zh_CN'>;
}
declare module 'vee-validate/dist/locale/zh_TW.js' {
  declare module.exports: $Exports<'vee-validate/dist/locale/zh_TW'>;
}
declare module 'vee-validate/dist/vee-validate.esm.js' {
  declare module.exports: $Exports<'vee-validate/dist/vee-validate.esm'>;
}
declare module 'vee-validate/dist/vee-validate.js' {
  declare module.exports: $Exports<'vee-validate/dist/vee-validate'>;
}
declare module 'vee-validate/dist/vee-validate.min.js' {
  declare module.exports: $Exports<'vee-validate/dist/vee-validate.min'>;
}
declare module 'vee-validate/tests/dictionary.js' {
  declare module.exports: $Exports<'vee-validate/tests/dictionary'>;
}
declare module 'vee-validate/tests/errorBag.js' {
  declare module.exports: $Exports<'vee-validate/tests/errorBag'>;
}
declare module 'vee-validate/tests/helpers/index.js' {
  declare module.exports: $Exports<'vee-validate/tests/helpers/index'>;
}
declare module 'vee-validate/tests/helpersTest.js' {
  declare module.exports: $Exports<'vee-validate/tests/helpersTest'>;
}
declare module 'vee-validate/tests/listeners.js' {
  declare module.exports: $Exports<'vee-validate/tests/listeners'>;
}
declare module 'vee-validate/tests/rules/after.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/after'>;
}
declare module 'vee-validate/tests/rules/alpha_dash.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/alpha_dash'>;
}
declare module 'vee-validate/tests/rules/alpha_num.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/alpha_num'>;
}
declare module 'vee-validate/tests/rules/alpha_spaces.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/alpha_spaces'>;
}
declare module 'vee-validate/tests/rules/alpha.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/alpha'>;
}
declare module 'vee-validate/tests/rules/before.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/before'>;
}
declare module 'vee-validate/tests/rules/between.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/between'>;
}
declare module 'vee-validate/tests/rules/confirmed.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/confirmed'>;
}
declare module 'vee-validate/tests/rules/credit_card.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/credit_card'>;
}
declare module 'vee-validate/tests/rules/date_between.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/date_between'>;
}
declare module 'vee-validate/tests/rules/date_format.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/date_format'>;
}
declare module 'vee-validate/tests/rules/decimal.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/decimal'>;
}
declare module 'vee-validate/tests/rules/digits.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/digits'>;
}
declare module 'vee-validate/tests/rules/dimensions.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/dimensions'>;
}
declare module 'vee-validate/tests/rules/email.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/email'>;
}
declare module 'vee-validate/tests/rules/ext.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/ext'>;
}
declare module 'vee-validate/tests/rules/image.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/image'>;
}
declare module 'vee-validate/tests/rules/in.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/in'>;
}
declare module 'vee-validate/tests/rules/ip.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/ip'>;
}
declare module 'vee-validate/tests/rules/max_value.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/max_value'>;
}
declare module 'vee-validate/tests/rules/max.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/max'>;
}
declare module 'vee-validate/tests/rules/mimes.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/mimes'>;
}
declare module 'vee-validate/tests/rules/min_value.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/min_value'>;
}
declare module 'vee-validate/tests/rules/min.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/min'>;
}
declare module 'vee-validate/tests/rules/not_in.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/not_in'>;
}
declare module 'vee-validate/tests/rules/numeric.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/numeric'>;
}
declare module 'vee-validate/tests/rules/regex.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/regex'>;
}
declare module 'vee-validate/tests/rules/required.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/required'>;
}
declare module 'vee-validate/tests/rules/size.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/size'>;
}
declare module 'vee-validate/tests/rules/url.js' {
  declare module.exports: $Exports<'vee-validate/tests/rules/url'>;
}
declare module 'vee-validate/tests/utils.js' {
  declare module.exports: $Exports<'vee-validate/tests/utils'>;
}
declare module 'vee-validate/tests/validator.1.js' {
  declare module.exports: $Exports<'vee-validate/tests/validator.1'>;
}
declare module 'vee-validate/tests/validator.js' {
  declare module.exports: $Exports<'vee-validate/tests/validator'>;
}
