// flow-typed signature: 0749d9016c8d7e148fdf3a8a3b5e2c49
// flow-typed version: <<STUB>>/vinyl-source-stream_v^1.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vinyl-source-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vinyl-source-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vinyl-source-stream/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vinyl-source-stream/index' {
  declare module.exports: $Exports<'vinyl-source-stream'>;
}
declare module 'vinyl-source-stream/index.js' {
  declare module.exports: $Exports<'vinyl-source-stream'>;
}
declare module 'vinyl-source-stream/test.js' {
  declare module.exports: $Exports<'vinyl-source-stream/test'>;
}
