// flow-typed signature: 8e5d1749f04ea43950bf105f0144cc12
// flow-typed version: <<STUB>>/vue-translated_v^0.4.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-translated'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-translated' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-translated/dist/index' {
  declare module.exports: any;
}

declare module 'vue-translated/example/i18n/formats/en-US' {
  declare module.exports: any;
}

declare module 'vue-translated/example/i18n/index' {
  declare module.exports: any;
}

declare module 'vue-translated/example/i18n/messages/en-US' {
  declare module.exports: any;
}

declare module 'vue-translated/example/index' {
  declare module.exports: any;
}

declare module 'vue-translated/src/index' {
  declare module.exports: any;
}

declare module 'vue-translated/vue.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-translated/dist/index.js' {
  declare module.exports: $Exports<'vue-translated/dist/index'>;
}
declare module 'vue-translated/example/i18n/formats/en-US.js' {
  declare module.exports: $Exports<'vue-translated/example/i18n/formats/en-US'>;
}
declare module 'vue-translated/example/i18n/index.js' {
  declare module.exports: $Exports<'vue-translated/example/i18n/index'>;
}
declare module 'vue-translated/example/i18n/messages/en-US.js' {
  declare module.exports: $Exports<'vue-translated/example/i18n/messages/en-US'>;
}
declare module 'vue-translated/example/index.js' {
  declare module.exports: $Exports<'vue-translated/example/index'>;
}
declare module 'vue-translated/src/index.js' {
  declare module.exports: $Exports<'vue-translated/src/index'>;
}
declare module 'vue-translated/vue.config.js' {
  declare module.exports: $Exports<'vue-translated/vue.config'>;
}
