// flow-typed signature: 8af2320ca7a73f989f367c1ae0dd3a00
// flow-typed version: <<STUB>>/vueify_v^9.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vueify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vueify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vueify/lib/compiler' {
  declare module.exports: any;
}

declare module 'vueify/lib/compilers/babel' {
  declare module.exports: any;
}

declare module 'vueify/lib/compilers/coffee' {
  declare module.exports: any;
}

declare module 'vueify/lib/compilers/index' {
  declare module.exports: any;
}

declare module 'vueify/lib/compilers/jade' {
  declare module.exports: any;
}

declare module 'vueify/lib/compilers/less' {
  declare module.exports: any;
}

declare module 'vueify/lib/compilers/pug' {
  declare module.exports: any;
}

declare module 'vueify/lib/compilers/sass' {
  declare module.exports: any;
}

declare module 'vueify/lib/compilers/stylus' {
  declare module.exports: any;
}

declare module 'vueify/lib/ensure-require' {
  declare module.exports: any;
}

declare module 'vueify/lib/gen-id' {
  declare module.exports: any;
}

declare module 'vueify/lib/insert-css' {
  declare module.exports: any;
}

declare module 'vueify/lib/normalize' {
  declare module.exports: any;
}

declare module 'vueify/lib/style-rewriter' {
  declare module.exports: any;
}

declare module 'vueify/lib/template-compiler' {
  declare module.exports: any;
}

declare module 'vueify/plugins/extract-css' {
  declare module.exports: any;
}

declare module 'vueify/test/fixtures/script-import' {
  declare module.exports: any;
}

declare module 'vueify/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vueify/index' {
  declare module.exports: $Exports<'vueify'>;
}
declare module 'vueify/index.js' {
  declare module.exports: $Exports<'vueify'>;
}
declare module 'vueify/lib/compiler.js' {
  declare module.exports: $Exports<'vueify/lib/compiler'>;
}
declare module 'vueify/lib/compilers/babel.js' {
  declare module.exports: $Exports<'vueify/lib/compilers/babel'>;
}
declare module 'vueify/lib/compilers/coffee.js' {
  declare module.exports: $Exports<'vueify/lib/compilers/coffee'>;
}
declare module 'vueify/lib/compilers/index.js' {
  declare module.exports: $Exports<'vueify/lib/compilers/index'>;
}
declare module 'vueify/lib/compilers/jade.js' {
  declare module.exports: $Exports<'vueify/lib/compilers/jade'>;
}
declare module 'vueify/lib/compilers/less.js' {
  declare module.exports: $Exports<'vueify/lib/compilers/less'>;
}
declare module 'vueify/lib/compilers/pug.js' {
  declare module.exports: $Exports<'vueify/lib/compilers/pug'>;
}
declare module 'vueify/lib/compilers/sass.js' {
  declare module.exports: $Exports<'vueify/lib/compilers/sass'>;
}
declare module 'vueify/lib/compilers/stylus.js' {
  declare module.exports: $Exports<'vueify/lib/compilers/stylus'>;
}
declare module 'vueify/lib/ensure-require.js' {
  declare module.exports: $Exports<'vueify/lib/ensure-require'>;
}
declare module 'vueify/lib/gen-id.js' {
  declare module.exports: $Exports<'vueify/lib/gen-id'>;
}
declare module 'vueify/lib/insert-css.js' {
  declare module.exports: $Exports<'vueify/lib/insert-css'>;
}
declare module 'vueify/lib/normalize.js' {
  declare module.exports: $Exports<'vueify/lib/normalize'>;
}
declare module 'vueify/lib/style-rewriter.js' {
  declare module.exports: $Exports<'vueify/lib/style-rewriter'>;
}
declare module 'vueify/lib/template-compiler.js' {
  declare module.exports: $Exports<'vueify/lib/template-compiler'>;
}
declare module 'vueify/plugins/extract-css.js' {
  declare module.exports: $Exports<'vueify/plugins/extract-css'>;
}
declare module 'vueify/test/fixtures/script-import.js' {
  declare module.exports: $Exports<'vueify/test/fixtures/script-import'>;
}
declare module 'vueify/test/test.js' {
  declare module.exports: $Exports<'vueify/test/test'>;
}
