// flow-typed signature: cfd3660e9019c3db121ab2af0442f520
// flow-typed version: <<STUB>>/vueify-insert-css_v^1.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vueify-insert-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vueify-insert-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vueify-insert-css/example/insert' {
  declare module.exports: any;
}

declare module 'vueify-insert-css/test/insert' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vueify-insert-css/example/insert.js' {
  declare module.exports: $Exports<'vueify-insert-css/example/insert'>;
}
declare module 'vueify-insert-css/index' {
  declare module.exports: $Exports<'vueify-insert-css'>;
}
declare module 'vueify-insert-css/index.js' {
  declare module.exports: $Exports<'vueify-insert-css'>;
}
declare module 'vueify-insert-css/test/insert.js' {
  declare module.exports: $Exports<'vueify-insert-css/test/insert'>;
}
