// flow-typed signature: 142b1b941908e5934889ad8db88f9842
// flow-typed version: <<STUB>>/vuejs-datepicker_v^0.9.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuejs-datepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuejs-datepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuejs-datepicker/build/build' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/build/check-versions' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/build/dev-client' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/build/dev-server' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/build/utils' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/build/vue-loader.conf' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/build/webpack.base.conf' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/build/webpack.dev.conf' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/build/webpack.prod.conf' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/build/webpack.test.conf' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/config/dev.env' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/config/index' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/config/prod.env' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/config/test.env' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/dist/build' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/main' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/utils/DateLanguages' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/src/utils/DateUtils' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/test/unit/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/test/unit/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/test/unit/index' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/test/unit/karma.conf' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/test/unit/specs/Datepicker.spec' {
  declare module.exports: any;
}

declare module 'vuejs-datepicker/test/unit/specs/DateUtils.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuejs-datepicker/build/build.js' {
  declare module.exports: $Exports<'vuejs-datepicker/build/build'>;
}
declare module 'vuejs-datepicker/build/check-versions.js' {
  declare module.exports: $Exports<'vuejs-datepicker/build/check-versions'>;
}
declare module 'vuejs-datepicker/build/dev-client.js' {
  declare module.exports: $Exports<'vuejs-datepicker/build/dev-client'>;
}
declare module 'vuejs-datepicker/build/dev-server.js' {
  declare module.exports: $Exports<'vuejs-datepicker/build/dev-server'>;
}
declare module 'vuejs-datepicker/build/utils.js' {
  declare module.exports: $Exports<'vuejs-datepicker/build/utils'>;
}
declare module 'vuejs-datepicker/build/vue-loader.conf.js' {
  declare module.exports: $Exports<'vuejs-datepicker/build/vue-loader.conf'>;
}
declare module 'vuejs-datepicker/build/webpack.base.conf.js' {
  declare module.exports: $Exports<'vuejs-datepicker/build/webpack.base.conf'>;
}
declare module 'vuejs-datepicker/build/webpack.dev.conf.js' {
  declare module.exports: $Exports<'vuejs-datepicker/build/webpack.dev.conf'>;
}
declare module 'vuejs-datepicker/build/webpack.prod.conf.js' {
  declare module.exports: $Exports<'vuejs-datepicker/build/webpack.prod.conf'>;
}
declare module 'vuejs-datepicker/build/webpack.test.conf.js' {
  declare module.exports: $Exports<'vuejs-datepicker/build/webpack.test.conf'>;
}
declare module 'vuejs-datepicker/config/dev.env.js' {
  declare module.exports: $Exports<'vuejs-datepicker/config/dev.env'>;
}
declare module 'vuejs-datepicker/config/index.js' {
  declare module.exports: $Exports<'vuejs-datepicker/config/index'>;
}
declare module 'vuejs-datepicker/config/prod.env.js' {
  declare module.exports: $Exports<'vuejs-datepicker/config/prod.env'>;
}
declare module 'vuejs-datepicker/config/test.env.js' {
  declare module.exports: $Exports<'vuejs-datepicker/config/test.env'>;
}
declare module 'vuejs-datepicker/dist/build.js' {
  declare module.exports: $Exports<'vuejs-datepicker/dist/build'>;
}
declare module 'vuejs-datepicker/src/main.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/main'>;
}
declare module 'vuejs-datepicker/src/utils/DateLanguages.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/utils/DateLanguages'>;
}
declare module 'vuejs-datepicker/src/utils/DateUtils.js' {
  declare module.exports: $Exports<'vuejs-datepicker/src/utils/DateUtils'>;
}
declare module 'vuejs-datepicker/test/unit/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'vuejs-datepicker/test/unit/coverage/lcov-report/prettify'>;
}
declare module 'vuejs-datepicker/test/unit/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'vuejs-datepicker/test/unit/coverage/lcov-report/sorter'>;
}
declare module 'vuejs-datepicker/test/unit/index.js' {
  declare module.exports: $Exports<'vuejs-datepicker/test/unit/index'>;
}
declare module 'vuejs-datepicker/test/unit/karma.conf.js' {
  declare module.exports: $Exports<'vuejs-datepicker/test/unit/karma.conf'>;
}
declare module 'vuejs-datepicker/test/unit/specs/Datepicker.spec.js' {
  declare module.exports: $Exports<'vuejs-datepicker/test/unit/specs/Datepicker.spec'>;
}
declare module 'vuejs-datepicker/test/unit/specs/DateUtils.spec.js' {
  declare module.exports: $Exports<'vuejs-datepicker/test/unit/specs/DateUtils.spec'>;
}
