imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    image_directory: '%kernel.root_dir%/../web/uploads/images'
    image_uri: '/uploads/images'
    media_directory: '%kernel.root_dir%/../web/uploads/media'
    media_uri: '/uploads/media'
    recording_directory: '%kernel.root_dir%/../web/uploads/recordings/'
    recording_uri: 'uploads/recordings/'
    locale: en

fos_rest:
    param_fetcher_listener: true
    format_listener:
        rules:
            - { path: ^/api/v3/, priorities: [json], fallback_format: json, prefer_extension: false }
            - { path: ^/login, priorities: [json], fallback_format: json, prefer_extension: false }
            - { path: ^/logout, priorities: [json], fallback_format: json, prefer_extension: false }
            - { path: ^/, priorities: [html], fallback_format: html, prefer_extension: false }
    view:
        formats:
            rss: true
            json: true
            xml: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        view_response_listener:
            enabled: true
            force: false

framework:
#    cache:
#        app: cache.adapter.redis
#        default_redis_provider: "redis://localhost"
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    serializer: { enable_annotations: true, enabled: true }
    secret: '%env(SYMFONY_SECRET)%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    form_themes: ['bootstrap_3_layout.html.twig']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore

# Swiftmailer Configuration
swiftmailer:
    url : '%env(MAILER_URL)%'
    spool: { type: memory }

hybrid_auth:
    facebook:
        keys:
            key: '%facebook_key%'
            secret: '%facebook_secret%'
        callback: 'http://localhost:8000/login/facebook'
    twitter:
        keys:
            key: '%twitter_key%'
            secret: '%twitter_secret%'
        callback: 'http://localhost:8000/login/twitter'
    google:
        keys:
            key: '%google_key%'
            secret: '%google_secret%'
        callback: 'http://localhost:8000/login/google'
