app:
    resource: '@CoreBundle/Controller/'
    type: annotation
dashboard:
    resource: '@DashboardBundle/Controller/'
    type: annotation
logout:
    path: /logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"