core:
    resource: '@CoreBundle/Controller/'
    type: annotation
app:
    resource: '@AppBundle/Controller/'
    type: annotation
dashboard:
    resource: '@DashboardBundle/Controller/'
    type: annotation
logout:
    path: /logout
login:
    path: /login
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"