# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        webservice:
            id: core.user_repository
        in_memory:
            memory: ~

    access_control:
        - { path: ^/dashboard, roles: [ROLE_DJ,ROLE_STAFF]}
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path:   /logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            form_login:
                check_path: /login
                success_handler: core.authentication_handler
                failure_handler: core.authentication_handler
                require_previous_session: false
