# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        webservice:
             entity: { class: CoreBundle:User}
        in_memory:
            memory: ~

    access_control:
        - { path: ^/api/v3/private, role: [ROLE_DJ,ROLE_STAFF] }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            entry_point: core.authentication_handler
            access_denied_handler: core.access_handler
            logout:
                path:   /logout
                target: /
            remember_me:
                secret:   '%env(SYMFONY_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            form_login:
                check_path: /login
                success_handler: core.authentication_handler
                failure_handler: core.authentication_handler
                require_previous_session: false
        facebook:
            anonymous: ~
            entry_point: core.authentication_handler
            access_denied_handler: core.access_handler
            guard:
                authenticators:
                    - 'core.facebook_auth'
            remember_me:
                secret:   '%env(SYMFONY_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            form_login:
                check_path: /login/facebook
                success_handler: core.authentication_handler
                failure_handler: core.authentication_handler
                require_previous_session: false
        google:
            anonymous: ~
            entry_point: core.authentication_handler
            access_denied_handler: core.access_handler
            guard:
                authenticators:
                    - 'core.google_auth'
            remember_me:
                secret:   '%env(SYMFONY_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            form_login:
                check_path: /login/facebook
                success_handler: core.authentication_handler
                failure_handler: core.authentication_handler
                require_previous_session: false
        twitter:
            anonymous: ~
            entry_point: core.authentication_handler
            access_denied_handler: core.access_handler
            guard:
                authenticators:
                    - 'core.twitter_auth'
            remember_me:
                secret:  '%env(SYMFONY_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            form_login:
                check_path: /login/facebook
                success_handler: core.authentication_handler
                failure_handler: core.authentication_handler
                require_previous_session: false