# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
    core.normalize:
        class: 'Symfony\Component\Serializer\Serializer'
        arguments:
            0:
                - '@CoreBundle\Normalizer\PostNormalizer'
                - '@CoreBundle\Normalizer\AccountNormalizer'
                - '@CoreBundle\Normalizer\CategoryNormalizer'
                - '@CoreBundle\Normalizer\CommentNormalizer'
                - '@CoreBundle\Normalizer\DatatableNormalizer'
                - '@CoreBundle\Normalizer\DateTimeNormalizer'
                - '@CoreBundle\Normalizer\DjNormalizer'
                - '@CoreBundle\Normalizer\EventNormalizer'
                - '@CoreBundle\Normalizer\GenreNormalizer'
                - '@CoreBundle\Normalizer\ImageNormalizer'
                - '@CoreBundle\Normalizer\PaginatorNormalizer'
                - '@CoreBundle\Normalizer\ScheduleEntryNormalizer'
                - '@CoreBundle\Normalizer\EventNormalizer'
                - '@CoreBundle\Normalizer\ScheduleNormalizer'
                - '@CoreBundle\Normalizer\ShowNormalizer'
                - '@CoreBundle\Normalizer\StreamNormalizer'
                - '@CoreBundle\Normalizer\TagNormalizer'
                - '@CoreBundle\Normalizer\WrapperNormalizer'
        public: true
    CoreBundle\:
        resource: '../../src/CoreBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/CoreBundle/{Controller,Entity,Repository,DataFixtures,Helper}'
    CoreBundle\Service\:
        resource: '../../src/CoreBundle/Service/*'
        public: true
    CoreBundle\Normalizer\:
        resource: '../../src/CoreBundle/Normalizer/*'
        public: true
    BroadcastBundle\Service\:
        resource: '../../src/BroadcastBundle/Service/*'
        public: true
    core.access_handler:
         alias: CoreBundle\Handler\AccessDeniedHandler
         public: true
    core.facebook_auth:
        class: CoreBundle\Security\HybridAuthenticator
        arguments: ["@cr.hybrid_auth.facebook"]
    core.google_auth:
        class: CoreBundle\Security\HybridAuthenticator
        arguments: ["@cr.hybrid_auth.google"]
    core.twitter_auth:
        class: CoreBundle\Security\HybridAuthenticator
        arguments: ["@cr.hybrid_auth.twitter"]
    core.authentication_handler:
        class: CoreBundle\Handler\AuthenticationHandler
        autowire: true
    CoreBundle\Service\ImageUploadService:
        arguments: ['%image_directory%']
        public: true