# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    core.image_upload_service:
        class: CoreBundle\Service\ImageUploadService
        arguments: ['%image_directory%']

    core.user_repository:
        class: CoreBundle\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\User
    core.authentication_handler:
        class: CoreBundle\Handler\AuthenticationHandler
        arguments:
            - "@router"
            - "@session"
    core.show_repository:
        class: CoreBundle\Repository\ShowRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Show
    core.blog_repository:
        class: CoreBundle\Repository\BlogRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Blog
    core.comment_repository:
        class: CoreBundle\Repository\CommentRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Comment
    #service_name:
    #    class: CoreBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
