# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    core.facebook_auth:
        class: CoreBundle\Security\HybridAuthenticator
        arguments: ["@cr.hybrid_auth.facebook"]
    core.google_auth:
        class: CoreBundle\Security\HybridAuthenticator
        arguments: ["@cr.hybrid_auth.google"]
    core.twitter_auth:
        class: CoreBundle\Security\HybridAuthenticator
        arguments: ["@cr.hybrid_auth.twitter"]

    core.authentication_handler:
        class: CoreBundle\Handler\AuthenticationHandler
        arguments:
            - "@router"
            - "@session"
            - "@doctrine"
    core.access_handler:
        class: CoreBundle\Handler\AccessDeniedHandler
    core.image_upload_service:
        class: CoreBundle\Service\ImageUploadService
        arguments: ['%image_directory%','core.image_repository']

    brodcast.icecast:
        class: BroadcastBundle\Service\IcecastService
        arguments:
            - '@kernel'
#------------------------------------------------------------------------------------------------
    core.comment_voter:
        class: CoreBundle\Security\CommentVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        public: false
    core.post_voter:
        class: CoreBundle\Security\PostVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        public: false
    core.show_voter:
        class: CoreBundle\Security\ShowVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        public: false
#------------------------------------------------------------------------------------------------
    core.user_repository:
        class: CoreBundle\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\User
    core.show_repository:
        class: CoreBundle\Repository\ShowRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Show
    core.post_repository:
        class: CoreBundle\Repository\PostRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Post
    core.comment_repository:
        class: CoreBundle\Repository\CommentRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Comment
    core.tag_repository:
        class: CoreBundle\Repository\TagRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Tag
    core.category_repository:
        class: CoreBundle\Repository\CategoryRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Category
    core.genre_repository:
        class: CoreBundle\Repository\GenreRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Genre
    core.image_repository:
        class: CoreBundle\Repository\ImageRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Image
    core.event_repository:
        class: CoreBundle\Repository\EventRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Event
    core.stream_repository:
        class: CoreBundle\Repository\StreamRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CoreBundle\Entity\Stream
    #service_name:
    #    class: CoreBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
