<?php namespace ChapmanRadio;

$podcastcategories = array(
	'Arts' => array(
		'Arts'=>'Arts',
		'Arts > Design' => 'Design',
		'Arts > Fashion &amp; Beauty' => 'Fashion &amp; Beauty',
		'Arts > Food' => 'Food',
		'Arts > Literature' => 'Literature',
		'Arts > Performing Arts' => 'Performing Arts',
		'Arts > Visual Arts' => 'Visual Arts'
		),
	'Business' => array(
		'Business'=>'Business',
		'Business > Business News' => 'Business News',
		'Business > Careers' => 'Careers',
		'Business > Investing' => 'Investing',
		'Business > Management &amp; Marketing' => 'Management &amp; Marketing',
		'Business > Shopping' => 'Shopping'
		),
	'Comedy' => array(
		'Comedy'=>'Comedy'
		),
	'Education' => array(
		'Education'=>'Education',
		'Education > Education Technology' => 'Education Technology',
		'Education > Higher Education' => 'Higher Education',
		'Education > K-12' => 'K-12',
		'Education > Language Courses' => 'Language Courses',
		'Education > Training' => 'Training'
		),
	'Games &amp; Hobbies' => array(
		'Games &amp; Hobbies'=>'Games &amp; Hobbies',
		'Games &amp; Hobbies > Automotive' => 'Automotive',
		'Games &amp; Hobbies > Aviation' => 'Aviation',
		'Games &amp; Hobbies > Hobbies' => 'Hobbies',
		'Games &amp; Hobbies > Other Games' => 'Other Games',
		'Games &amp; Hobbies > Video Games' => 'Video Games',),
	'Government &amp; Organizations' => array(
		'Government &amp; Organizations'=>'Government &amp; Organizations',
		'Government &amp; Organizations > Local' => 'Local',
		'Government &amp; Organizations > National' => 'National',
		'Government &amp; Organizations > Non-Profit' => 'Non-Profit',
		'Government &amp; Organizations > Regional' => 'Regional',),
	'Health' => array(
		'Health'=>'Health',
		'Health > Alternative Health' => 'Alternative Health',
		'Health > Fitness &amp; Nutrition' => 'Fitness &amp; Nutrition',
		'Health > Self-Help' => 'Self-Help',
		'Health > Sexuality' => 'Sexuality',),
	'Kids &amp; Family' => array(
		'Kids &amp; Family'=>'Kids &amp; Family',),
	'Music' => array(
		'Music'=>'Music',),
	'News &amp; Politics' => array(
		'News &amp; Politics'=>'News &amp; Politics',),
	'Religion &amp; Spirituality' => array(
		'Religion &amp; Spirituality'=>'Religion &amp; Spirituality',
		'Religion &amp; Spirituality > Buddhism' => 'Buddhism',
		'Religion &amp; Spirituality > Christianity' => 'Christianity',
		'Religion &amp; Spirituality > Hinduism' => 'Hinduism',
		'Religion &amp; Spirituality > Islam' => 'Islam',
		'Religion &amp; Spirituality > Judaism' => 'Judaism',
		'Religion &amp; Spirituality > Other' => 'Other',
		'Religion &amp; Spirituality > Spirituality' => 'Spirituality',),
	'Science &amp; Medicine' => array(
		'Science &amp; Medicine'=>'Science &amp; Medicine',
		'Science &amp; Medicine > Medicine' => 'Medicine',
		'Science &amp; Medicine > Natural Sciences' => 'Natural Sciences',
		'Science &amp; Medicine > Social Sciences' => 'Social Sciences',),
	'Society &amp; Culture' => array(
		'Society &amp; Culture'=>'Society &amp; Culture',
		'Society &amp; Culture > History' => 'History',
		'Society &amp; Culture > Personal Journals' => 'Personal Journals',
		'Society &amp; Culture > Philosophy' => 'Philosophy',
		'Society &amp; Culture > Places &amp; Travel' => 'Places &amp; Travel',),
	'SportsController &amp; Recreation' => array(
		'SportsController &amp; Recreation'=>'SportsController &amp; Recreation',
		'SportsController &amp; Recreation > Amateur' => 'Amateur',
		'SportsController &amp; Recreation > College &amp; High School' => 'College &amp; High School',
		'SportsController &amp; Recreation > Outdoor' => 'Outdoor',
		'SportsController &amp; Recreation > Professional' => 'Professional',),
	'Technology' => array(
		'Technology'=>'Technology',
		'Technology > Gadgets' => 'Gadgets',
		'Technology > Tech News' => 'Tech News',
		'Technology > Podcasting' => 'Podcasting',
		'Technology > Software How-To' => 'Software How-To',),
	);